import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeContextProvider from "@/components/theme-provider";
import Navbar from "@/components/Navbar"; // Import client-side Navbar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900 dark:bg-gray-900 min-h-screen flex flex-col`}
      >
        <ThemeContextProvider>
          {/* Fixed Header with Navbar */}
          <Navbar />

          {/* Main Content */}
          <main className="flex-grow pt-16">{children}</main>

          {/* Footer (Always Present) */}
          <footer className="p-4 text-center border-t bg-gray-100 dark:bg-gray-800 dark:text-white">
            &copy; {new Date().getFullYear()} Pack the Feed. All rights reserved.
          </footer>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
